#include <stdlib.h>
#include "events.h"
// create events
Event s1 = {CONTROLLABLE, 0, SUP_DEBUG_STR("s1"), NULL};
Event f1 = {CONTROLLABLE, 1, SUP_DEBUG_STR("f1"), NULL};
Event s2 = {CONTROLLABLE, 2, SUP_DEBUG_STR("s2"), NULL};
Event f2 = {CONTROLLABLE, 3, SUP_DEBUG_STR("f2"), NULL};
Event t1 = {UNCONTROLLABLE, 4, SUP_DEBUG_STR("t1"), NULL};
Event t2 = {UNCONTROLLABLE, 5, SUP_DEBUG_STR("t2"), NULL};
Event s4 = {CONTROLLABLE, 6, SUP_DEBUG_STR("s4"), NULL};
Event f4 = {CONTROLLABLE, 7, SUP_DEBUG_STR("f4"), NULL};
Event s5 = {CONTROLLABLE, 8, SUP_DEBUG_STR("s5"), NULL};
Event f5 = {CONTROLLABLE, 9, SUP_DEBUG_STR("f5"), NULL};
Event s3 = {CONTROLLABLE, 10, SUP_DEBUG_STR("s3"), NULL};
Event f3 = {CONTROLLABLE, 11, SUP_DEBUG_STR("f3"), NULL};
Event m6 = {UNCONTROLLABLE, 12, SUP_DEBUG_STR("m6"), NULL};
Event m7 = {UNCONTROLLABLE, 13, SUP_DEBUG_STR("m7"), NULL};
Event t5 = {UNCONTROLLABLE, 14, SUP_DEBUG_STR("t5"), NULL};
Event p6 = {UNCONTROLLABLE, 15, SUP_DEBUG_STR("p6"), NULL};
Event p7 = {UNCONTROLLABLE, 16, SUP_DEBUG_STR("p7"), NULL};
Event t3 = {UNCONTROLLABLE, 17, SUP_DEBUG_STR("t3"), NULL};
Event t4 = {UNCONTROLLABLE, 18, SUP_DEBUG_STR("t4"), NULL};

Event *controllable_event_list[CONTROLLABLE_EVENTS_COUNT] = {&s1,&f1,&s2,&f2,&s4,&f4,&s5,&f5,&s3,&f3};